[build]
  publish = "dist/"
  command = "npm run prod"

[build.environment]
  NODE_ENV = "production"
  ELEVENTY_ENV = "staging"

[context.production.environment]
  ELEVENTY_ENV = "production" # excludes Forestry drafts from production build
